#pragma once

#include "jwaoo_hw.h"

enum
{
	JWAOO_BATT_POLL = KE_FIRST_MSG(TASK_JWAOO_APP),

	JWAOO_REBOOT,
	JWAOO_SHUTDOWN,
	JWAOO_KEY_LOCK,

	JWAOO_LED1_BLINK,
	JWAOO_LED2_BLINK,
	JWAOO_MOTO_BLINK,
	JWAOO_MOTO_BOOST,

	JWAOO_KEY1_REPEAT_TIMER,
	JWAOO_KEY1_LONG_CLICK_TIMER,
	JWAOO_KEY1_MULTI_CLICK_TIMER,

	JWAOO_KEY2_REPEAT_TIMER,
	JWAOO_KEY2_LONG_CLICK_TIMER,
	JWAOO_KEY2_MULTI_CLICK_TIMER,

	JWAOO_KEY3_REPEAT_TIMER,
	JWAOO_KEY3_LONG_CLICK_TIMER,
	JWAOO_KEY3_MULTI_CLICK_TIMER,

	JWAOO_KEY4_REPEAT_TIMER,
	JWAOO_KEY4_LONG_CLICK_TIMER,
	JWAOO_KEY4_MULTI_CLICK_TIMER,
};

enum
{
	JWAOO_APP_ACTIVE,
	JWAOO_APP_SUSPEND,
	JWAOO_APP_DEEP_SLEEP,
	JWAOO_APP_STATE_MAX
};

extern bool jwaoo_suspended;

void jwaoo_task_init(void);
void jwaoo_set_deep_sleep_enable(bool enable);
void jwaoo_set_suspend_enable(bool enable, bool force);
